project:
  type: website
  output-dir: docs

website:
  title: "Charting human biology using AI for Precision Health & Precision Medicine"
  sidebar:
    background: primary
    #logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/BRICAI2023/charting_human_biology_using_AI
        text: GitHub
    style: docked
    contents:
      - href: index.qmd
        text: Home
      - href: schedule.qmd
        text: Schedule
      - href: materials.qmd
        text: Call for poster presentations
      - href: organizers.qmd
        text: Organizers
   
format:
  html:
    theme: cosmo
    # css: styles.css
    toc: true

execute:
  freeze: auto

