---
title: "CALL FOR POSTER PRESENTATIONS"
---

Please submit your abstracts using the link below. 

### Topics of interest include but not limited to

• Models unraveling biological networks generating actionable insights on perturbations and recovery mechanisms

• Building patient digital twins

• Novel methods for integrating multi-omics/multi-modality data to identify disease subtypes

• Novel methods for target identification and validation using multi-omics/multi-modality data

• Chemo-multi-omics approaches for drug discovery

• Biomarker discovery

• Explainability/Interpretability of the models

• Mechanistic and Hybrid models

• AI/ML powered drug discovery strategies utilizing human-centered bio-technologies alternative to animal studies

• Limitations of AI/ML and where new biosensing tools are needed/developed (such as single cell transcriptomics versus spatial single cell transcriptomics)

### Registration Link

**Please register through [this google form]( https://docs.google.com/forms/d/e/1FAIpQLScq83so2aQntCTdwQauWHZQdFnU6w0FtqrrrOoqub6pmgV14w/viewform?usp=sf_link) **

Note:
This hybrid (in person and virtual) event is free of charge and open to public. However, space is limited for in person attendance and poster presenters will be prioritized. There is no limit for online attendance. We would look forward to meeting you all!
Sincerely,
Organization Committee



