---
title: "Schedule"
---

The event will be held on Nov 16th.

Agenda (Timezone EST):

8:00am – 8:45 am
Registration and Coffee
 
8:55 am - 9:30 am – Overview of the Agenda and Welcome Remarks

Ilknur Icke, Director of Applied Machine Learning, Bayer

Emmanuelle di Tomaso,  Global Head, Translational Sciences Oncology, Bayer

Sai Jasti, SVP, Head of Data Science and AI, Bayer
 
9:30 am - 11:00am
Session 1. Understanding health and disease for Precision Health and Precision Medicine 

Moderator:

9:30am - 10:00 am Virginia Savova, PhD. Senior Director, Global Head of Single-cell Biology, Sanofi

From Single-cell Biology To Cell-Centric Drug Discovery

10am - 10:30am Matthew Bernstein, PhD.  Principal Scientist, Immunitas Therapeutics

Annotating cell types and cell states in single-cell omics data: a challenging problem

10:30am - 11am Shantanu Singh, Ph.D.  Senior Group Leader at the Broad Institute

Finding disease phenotypes and candidate therapeutics using images: Cell Painting
 
Coffee Break - refreshments will be served (30 mins)
 
11:30am- 1:00pm
Session 2. Designing Therapeutics for Precision Medicine

Moderator: Matteo Aldeghi, Director of Machine Learning Research, Bayer

11:30 am - 12pm Elizabeth Wood, PhD.  President and Chief Executive Officer, JURA Bio, Inc

Variational Synthesis Atlas of Human T Cell Repertoires (VISTA-T): Generative Library Design Enables Large Scale Discovery of Therapeutically Relevant TCRs

13pm - 12:30pm Sherlock Hu, PhD.  CIO, GV20 Therapeutics

AI for Target Identification and Antibody Discovery

12:30pm - 1pm Michal Warchol, PhD. Executive Vice President, Ardigen

Multimodal approach to phenotype-guided virtual screening of small molecules

1:00pm – 2:00pm Lunch Break - Poster and Networking Session at BRIC 6th floor (lunch will be provided)

Participating companies: Ardigen, Leal Health, Superluminal Medicines
 
2:00pm - 3:30pm
Session 3. Conducting Better Clinical Trials for Precision Medicine

Moderator:

2pm - 2:30pm Gustavo Arango-Argoty, Ph.D.  Associate Director, Applied Data Science, AstraZeneca

Pretrained transformers applied to clinical studies improve predictions of treatment efficacy and associated biomarkers

2:30pm - 3pm James Lindsay, PhD. Director of Software Engineering, Department of Data Science, Dana-Farber Cancer Institute

Leveraging artificial intelligence predictions of treatment change to time out reach for enrollment in precision medicine clinical trials

3pm - 3:30pm Charles Fisher, PhD. CEO, Unlearn.AI

Enabling Efficient Clinical Trials with Generative Models for Clinical Timeseries

Coffee Break - refreshments will be provided (30 mins)
 
4pm - 4:15pm Dylan Morris, Managing Director, Insight Partners

Emerging Trends from a Venture Capitalist Perspective

4:15pm - 4:20pm Closing Remarks
Ming Tommy Tang, PhD. Director of Computational Biology, Immunitas Therapeutics

4:20 End of workshop
